[package]
name = "oqueue"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"

[dependencies]
readonly = "0.1.3"
termcolor = "1.0"

[dev-dependencies]
num_cpus = "1.0"
rayon = "1.0"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "oqueue_doc_cfg"]
